opp_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^', include('django.contrib.auth.urls')), # login, logout, password_change, etc.
    url(r'^', include('website.urls')),
    url(r'^user/', include('accounts.urls')),
    url(r'^feedhandler/', include('feedhandler.urls')),
    url(r'^accesslogger/', include('accesslogger.urls')),
]

handler403 = 'website.views.err403'
handler404 = 'website.views.err404'
handler500 = 'website.views.err500'

website/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^page/(?P<page>\d+)$', views.index, name='index_page'),
    #url(r'^qa/$', views.qa, name='qa'),
    url(r'^t/(?P<topic_name>\w+)$', views.topic, name='topic'),
    url(r'^feed.xml$', views.atom_feed, name='feed'),
    url(r'^sources$', views.sources, name='sources'),
    url(r'^sourcesadmin$', views.sourcesadmin, name='sourcesadmin'),
    url(r'^edit-source$', views.edit_source, name='edit_source'),
    url(r'^edit-doc$', views.edit_doc, name='edit_doc'),
]

website/models.py
import hashlib
from operator import itemgetter
from django.db import models
from django.contrib.auth.models import User

class Cat(models.Model):
    cat_id = models.AutoField(primary_key=True)
    label = models.CharField(unique=True, max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'cats'

    def num_training_pos(self):
        """number of positive training documents"""
        return self.doc_set.filter(doc2cat__is_training=1, doc2cat__strength=100).count()

    def num_training_neg(self):
        """number of negative training documents"""
        return self.doc_set.filter(doc2cat__is_training=1, doc2cat__strength=0).count()

    def __str__(self):
        return self.label
    
class Source(models.Model):
    SOURCETYPES = (
        ('personal', 'personal website'),
        ('repo', 'repository'),
        ('journal', 'journal'),
        ('blog', 'weblog'),
    )
    source_id = models.AutoField(primary_key=True)
    sourcetype = models.CharField(max_length=16, choices=SOURCETYPES, default='personal')
    url = models.URLField(max_length=512)
    urlhash = models.CharField(unique=True, max_length=32, editable=False)
    status = models.SmallIntegerField(blank=True, default=0)
    found_date = models.DateTimeField()
    last_checked = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=128, blank=True, null=True)
    default_author = models.CharField(max_length=128, blank=True, null=True)

    def save(self, *args, **kwargs):
        """set urlhash to MD5(url)"""
        self.urlhash = hashlib.md5(self.url.encode('utf-8')).hexdigest()
        super().save(*args, **kwargs)
        
    def __str__(self):
        return '{}. {} ({})'.format(self.source_id, self.name, self.url[:40])

    def num_links(self):
        return self.link_set.count()

    def num_docs(self):
        return self.doc_set.count()
        
    class Meta:
        db_table = 'sources'
        ordering = ['name']

class Link(models.Model):
    link_id = models.AutoField(primary_key=True)
    url = models.URLField(max_length=512)
    urlhash = models.CharField(max_length=32, editable=False)
    status = models.SmallIntegerField(blank=True, default=0)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    #source_id = models.IntegerField()
    found_date = models.DateTimeField()
    last_checked = models.DateTimeField(blank=True, null=True)
    etag = models.CharField(max_length=255, blank=True, null=True)
    filesize = models.IntegerField(blank=True, null=True)
    #doc_id = models.IntegerField()
    doc = models.ForeignKey('Doc', on_delete=models.SET_NULL, null=True)

    def save(self, *args, **kwargs):
        """set urlhash to MD5(url)"""
        self.urlhash = hashlib.md5(self.url.encode('utf-8')).hexdigest()
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}. Source {} -> {}'.format(self.link_id, self.source, self.url[:60])

    class Meta:
        db_table = 'links'
        unique_together = (('source', 'urlhash'),)

class Doc(models.Model):
    DOCTYPES = (
        ('article', 'article'),
        ('book', 'book'),
        ('chapter', 'book chapter'),
        ('thesis', 'thesis'),
        ('review', 'review'),
        ('blogpost', 'blogpost'),
    )
    doc_id = models.AutoField(primary_key=True)
    status = models.SmallIntegerField(blank=True, default=1)
    url = models.URLField(max_length=512)
    urlhash = models.CharField(unique=True, max_length=32, editable=False)
    doctype = models.CharField(max_length=16, choices=DOCTYPES, default='article')
    filetype = models.CharField(max_length=8, blank=True, null=True)
    filesize = models.IntegerField(blank=True, null=True)
    found_date = models.DateTimeField(blank=True, null=True)
    earlier_id = models.IntegerField(blank=True, null=True)
    authors = models.CharField(max_length=255, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    abstract = models.TextField(blank=True, null=True)
    numwords = models.PositiveIntegerField(blank=True, null=True)
    numpages = models.PositiveSmallIntegerField(blank=True, null=True)
    # The following two fields are there for documents whose source has gone dead
    source_url = models.URLField(max_length=512, blank=True, null=True)
    source_name = models.CharField(max_length=255, blank=True, null=True)
    source = models.ForeignKey(Source, on_delete=models.SET_NULL, null=True)
    hidden = models.BooleanField(default=False)
    meta_confidence = models.IntegerField(blank=True, null=True)
    is_paper = models.IntegerField(blank=True, null=True)
    is_philosophy = models.IntegerField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)

    cats = models.ManyToManyField(Cat, through='Doc2Cat')

    def _cats(self):
        """
        returns list of cats paired with strengths >= 50 rounded to
        multiples of 10, e.g. [('Epistemology', 70),...]
        """
        ms = self.doc2cat_set.filter(strength__gte=50)
        pairs = [(m.cat.label, int(round(m.strength, -1))) for m in ms]
        return sorted(pairs, key=itemgetter(1), reverse=True)
    topics = property(_cats)
    
    def _low_confidence(self):
        return self.meta_confidence <= 60
    low_confidence = property(_low_confidence)

    def _is_blogpost(self):
        return self.doctype == 'blogpost'
    is_blogpost = property(_is_blogpost)

    def save(self, *args, **kwargs):
        """set urlhash to MD5(url)"""
        self.urlhash = hashlib.md5(self.url.encode('utf-8')).hexdigest()
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}. {} ({})'.format(self.doc_id, self.title[:40], self.url[:40])
        
    class Meta:
        db_table = 'docs'
        ordering = ['-found_date']

class AuthorName(models.Model):
    name_id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=64)
    last_searched = models.DateTimeField(blank=True, null=True)
    is_name = models.BooleanField(default=True)

    class Meta:
        db_table = 'author_names'
    
    def __str__(self):
        return '{}. {}'.format(self.name_id, self.name)

class Journal(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=64)

    class Meta:
        db_table = 'journals'
    
    def __str__(self):
        return self.name
        
class Doc2Cat(models.Model):
    doc2cat_id = models.AutoField(primary_key=True)
    doc = models.ForeignKey(Doc, on_delete=models.CASCADE)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)
    strength = models.IntegerField(blank=True, null=True)
    is_training = models.BooleanField(default=False)

    class Meta:
        db_table = 'docs2cats'
        unique_together = (('doc', 'cat'),)

    def __str__(self):
        return 'Doc {} -> Cat {}'.format(self.doc_id, self.cat_id)
        
class Doc2User(models.Model):
    doc2user_id = models.AutoField(primary_key=True)
    doc = models.ForeignKey(Doc, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    strength = models.IntegerField(blank=True, null=True)
    is_training = models.BooleanField(default=False)

    class Meta:
        db_table = 'docs2users'
        unique_together = (('doc', 'user'),)

    def __str__(self):
        return 'Doc {} -> User {}'.format(self.doc_id, self.user_id)

website/forms.py
from django.forms import ModelForm, HiddenInput
from .models import *

class SourceForm(ModelForm):
    class Meta:
        model = Source
        fields = ('url', 'sourcetype', 'default_author', 'name')

class DocEditForm(ModelForm):
    class Meta:
        model = Doc
        fields = ('doc_id', 'authors', 'title', 'abstract', 'hidden')
        #widgets = {'doc_id': HiddenInput()}

website/views.py
import re
import requests
from collections import defaultdict
from datetime import datetime, timedelta
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.utils.timezone import utc
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Doc, Source
from .forms import SourceForm, DocEditForm
from django.utils.feedgenerator import Atom1Feed
from feedhandler import superfeedr

def index(request, page=1):
    doclist = Doc.objects.all()
    if not request.user.is_staff:
        doclist = doclist.filter(hidden=False)
    return list_docs(request, doclist, page=page)

def topic(request, topic_name, min_strength=50, page=1):
    doclist = Doc.objects.filter(
        cats__label=topic_name,
        doc2cat__strength__gte=min_strength
    )
    if not request.user.is_staff:
        doclist = doclist.filter(hidden=False)
    return list_docs(request, doclist, topic=topic_name, page=page)

def list_docs(request, doclist, topic=None, page=1):
    paginator = Paginator(doclist, 30) # 30 per page
    try:
        MAX_PAGE = 10
        page = page if int(page) <= MAX_PAGE else 1
        docs = paginator.page(page)
    except:
        # no such page
        raise
        docs = paginator.page(1)
    for doc in docs:
        doc.deltadate = seconds_since(doc.found_date)
        doc.short_url = short_url(doc.url)
    context = { 'docs': docs, 'topic': topic }
    if request.user.is_staff:
        context['editform'] = DocEditForm()
    return render(request, 'website/doclist.html', context)

def seconds_since(date):
    if not date:
        return 1000000
    now = datetime.utcnow().replace(tzinfo=utc)
    timediff = now - date
    return timediff.total_seconds()

def short_url(url):
    if not url:
        return '#'
    url = re.sub(r'^https?://', '', url)
    if len(url) > 80:
        url = url[:38] + '...' + url[-39:]
    #url = re.sub(r'(\.\w+)$', r'<b>\1</b>', url)
    return url
    
def sources(request):
    srclist = Source.objects.all()
    context = {}
    for cls in ('personal', 'repo', 'journal', 'blog'):
        context[cls] = [src for src in srclist if src.sourcetype == cls]
    return render(request, 'website/sourceslist.html', context)

@staff_member_required
@csrf_exempt
def sourcesadmin(request):
    if request.method == 'POST':
        try:
            src = Source.objects.get(source_id=request.POST.get('source_id'))
            if request.POST.get('action') == 'get_new_url':
                try:
                    r = requests.head(src.url, allow_redirects=True, timeout=5)
                    return HttpResponse(r.url)
                except Exception as e:
                    return HttpResponse('[requests error: {}]'.format(e))
            elif request.POST.get('action') == 'change_url':
                src.url = request.POST.get('new_url')
                src.status = 1
                src.save()
                return HttpResponse('URL changed')
            elif request.POST.get('action') == 'remove':
                src.delete()
                return HttpResponse('Source deleted')
            return HttpResponse('Unknown action')
        except Exception as e:
            return HttpResponse('Oh dear: {}'.format(e))

    srclist = Source.objects.all()

    blogsources = []
    subscribed_urls = superfeedr.subscribed_urls()
    for src in srclist:
        if src.sourcetype == 'blog':
            src.subscribed = (src.url in subscribed_urls)
            if src.url in subscribed_urls:
                subscribed_urls.remove(src.url)
            blogsources.append(src)
    for url in subscribed_urls:
        # any subscribed urls that aren't in our db:
        src = Source(url=url, name=url, sourcetype='blog')
        src.subscribed = True
        blogsources.append(src)

    context = { 
        'sourcetypes': [
            { 
                'heading': 'Personal pages', 
                'sources': [src for src in srclist if src.sourcetype == 'personal'],
            },
            { 
                'heading': 'Repositories', 
                'sources': [src for src in srclist if src.sourcetype == 'repo'],
            },
            { 
                'heading': 'Open Access Journals', 
                'sources': [src for src in srclist if src.sourcetype == 'journal'],
            },
            { 
                'heading': 'Weblogs', 
                'sources': blogsources, 
            },
        ]
    }

    return render(request, 'website/sourcesadmin.html', context)

def qa(request):
    return render(request, 'website/qa.html')

# edit doc popup form:
@staff_member_required
def edit_doc(request): 
    try:
        doc = Doc.objects.get(doc_id=request.POST['doc_id'])
    except:
        return HttpResponse('Doc object does not exist')
    doc_was_hidden = doc.hidden
    form = DocEditForm(instance=doc, data=request.POST)
    if form.is_valid():
        if form.cleaned_data.get('hidden'):
            # 'Discard Entry' was clicked -- remove doc from db:
            doc.delete()
            return HttpResponse('OK, entry deleted')
        else:
            doc = form.save(commit=False)
            if doc_was_hidden:
                doc.found_date = datetime.utcnow().replace(tzinfo=utc)
            doc.save()
            return HttpResponse('OK, entry updated')
    else:
        return HttpResponse('invalid form')
        
# bookmarklet form for adding source pages:
@staff_member_required
def edit_source(request):
    form = SourceForm(request.POST or request.GET)
    if request.method == 'POST' and form.is_valid():
        try:
            src = form.save()
        except IntegrityError:
            return HttpResponse('Address already in database')
        if form.cleaned_data['sourcetype'] == 'blog':
            # register new blog subscription on superfeedr:
            callback = request.build_absolute_uri(reverse('new_post', args=[src.source_id]))
            try:
                superfeedr.subscribe(url=src.url, callback_url=callback)
            except Exception as e:
                msg = 'could not register blog on superfeedr! {}'.format(e)
                return HttpResponse(msg)
        return HttpResponse('OK')
    if Source.objects.filter(url=request.GET.get('url')).exists():
        return HttpResponse('Address already in database')
    context = { 'form': form, 'related': [] }
    if request.GET.get('default_author'):
        surname = request.GET.get('default_author').split()[-1]
        context['related'].extend(Source.objects.filter(default_author__endswith=surname))
    return render(request, 'website/edit_source.html', context)

# atom feed:
def atom_feed(request):
    feed = Atom1Feed(
        title='Philosophical Progress',
        link='http://www.philosophicalprogress.org/',
        description='New online papers in philosophy',
        feed_url='http://www.philosophicalprogress.org/feed.xml'
    )
    docs = Doc.objects.filter(
        status=1,
        hidden=False,
        found_date__lt=datetime.now().date(),
        found_date__gte=datetime.now().date()-timedelta(days=7)
    )
    
    docs_per_day = defaultdict(list)
    for doc in docs:
        daystr = doc.found_date.strftime('%Y%m%d') # for sorting
        docs_per_day[daystr].append(doc)

    for k in sorted(docs_per_day.keys(), reverse=True):
        day_text = ''
        day_docs = sorted(docs_per_day[k], key=lambda doc: (doc.is_blogpost, doc.authors))
        for doc in day_docs:
            authors = doc.source_name if doc.is_blogpost else doc.authors
            day_text += '<b>{}: <a href="{}">{}</a></b>'.format(authors, doc.url, doc.title)
            day_text += ' ({}, {} words)<br />'.format(doc.filetype, doc.numwords)
            day_text += ' <div>{}</div><br />\n'.format(doc.abstract)
        d = day_docs[0].found_date
        pubdate = datetime(d.year, d.month, d.day, 23, 59)
        feed.add_item(
            author_name = 'Philosophical Progress',
            title = 'Articles and blog posts found on {}'.format(d.strftime('%d %B %Y')),
            link = 'http://www.philosophicalprogress.org/',
            description = day_text, 
            pubdate = pubdate,
            updateddate = pubdate
        )

    # TODO: cache?
    return HttpResponse(feed.writeString('utf-8'), content_type=feed.mime_type)

_illegal_xml_chars_RE = re.compile(u'[\x00-\x08\x0b\x0c\x0e-\x1F\uD800-\uDFFF\uFFFE\uFFFF]')
def escape_illegal_chars(val, replacement='?'):
    return _illegal_xml_chars_RE.sub(replacement, val)    


# error handlers

def err404(request):
    return HttpResponse('404')
    
def err403(request):
    return HttpResponse('403')

def err500(request):
    return HttpResponse('500')

website/templates/website/doclist.html
{% extends "base.html" %}

{% block xxxfiltermenu %}

<div id="filtermenu">
Showing 
<span class="dropdown dropdown-select" id="dropdown1">
  <button class="btn btn-default dropdown-toggle" type="button" id="filtermenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    new papers and blog posts
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">new papers</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">new blog posts</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">new papers and blog posts</a></li>
  </ul>
</span>
in
<span class="dropdown dropdown-select" id="dropdown2">
  <button class="btn btn-default dropdown-toggle" type="button" id="filtermenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    all areas of philosophy
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">new papers</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">new blog posts</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">new papers and blog posts</a></li>
  </ul>
</span>


<script>

$('#dropdown1').on('click', '.dropdown-menu li a', function() { 
  var target = $(this).html();

	   //Adds active class to selected item
	   $(this).parents('.dropdown-menu').find('li').removeClass('active');
	   $(this).parent('li').addClass('active');

	   //Displays selected text on dropdown-toggle button
	   $(this).parents('.dropdown-select').find('.dropdown-toggle').html(target + ' <span class="caret"></span>');
	});

</script>

<!--form name="filterform" id="filterform" action="{{ rootdir }}" method="GET" onsubmit="return false">
  <select size="1" name="type" onchange="updateDocList()">
    <option value="all">new papers and blog posts</option>
    <option value="papers"{% if doctype == 'papers' %} selected="selected"{% endif %}>new papers</option>
    <option value="blogposts"{% if doctype == 'blogposts' %} selected="selected"{% endif %}>new blog posts</option>
  </select>
  in
</form-->
</div>

{% endblock %}

{% block content %}

<div id="maindiv" class="col-md-9">
  <ol class='doclist'>
  {% for doc in docs %}
    <li class="doc{% if doc.hidden %} dochidden{% endif %}{% if doc.is_blogpost %} blogpost{% endif %}">
      <div class='daysep'>{{ doc.deltadate }}</div>
      {% if request.user.is_staff %}
        <button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#editModal" onclick="edit({{ doc.doc_id }})">Edit</button>
      {% endif %}
      <div class='iAuthor'>
        <a href='{{ doc.url }}' id='authors{{doc.doc_id}}'>{{ doc.authors }}</a>
      </div>
      {% if doc.is_blogpost %}
        <div class='iBlogname'>
          <a href='{{ doc.url }}' id='blogname{{doc.doc_id}}'>{{ doc.source_name }}</a>
        </div>
      {% endif %}
      <div class='iTitle'>
        <a href='{{ doc.url }}' id='title{{doc.doc_id}}'>{{ doc.title|safe }}</a>
      </div>
      <div class='iUrl'>
        <a href='{{ doc.url }}'>{{ doc.short_url|safe }} ({{ doc.filetype|upper }}, {{ doc.numwords }} words)</a>
      </div>
      <div class='iAbstract' id='abstract{{doc.doc_id}}'>{{ doc.abstract|safe }}</div>
      {% if doc.topics %}
      <div class='iTopics'>
        {% for topic, strength in doc.topics %}
           <a class='iTopic{{strength}}' href='{% url 'topic' topic|lower %}'>{{ topic }}</a>
        {% endfor %}
      </div>
      {% endif %}
      <div class='iFooter'>
        <span>Found {{ doc.found_date|timesince }} ago on <a href="{{ doc.source_url }}">{{ doc.source_name }}</a></span>
        {% if request.user.is_staff %}
          <span>[doc {{ doc.doc_id }}]</span>
          <span>[conf {{ doc.meta_confidence }}]</span>
          <span>[paper: {{ doc.is_paper }}]</span>
          <span>[phil: {{ doc.is_philosophy }}]</span>
        {% endif %}
      </div>
    </li>
  {% endfor %}
  </ol>
  <nav>
    <ul class="pager">
      {% if docs.has_previous %}
        <li><a href="{% url 'index_page' docs.previous_page_number %}">Newer Entries</a></li>
      {% endif %}
      {% if docs.has_next and docs.number < 10 %}
        <li><a href="{% url 'index_page' docs.next_page_number %}">Older Entries</a></li>
      {% endif %}
    </ul>
  </nav>

</div>

<div id="sidebar" class='col-md-3'>
</div>

{% if request.user.is_staff %}
<!-- Modal -->
<div class="modal" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="editform" action="/edit-doc" method="post">
        {% csrf_token %}
        <input type="hidden" name="doc_id" id="id_doc_id" />
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Edit entry</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="id_authors">Authors:</label>
            <input id="id_authors" maxlength="255" name="authors" type="text" class="form-control" />
          </div>
          <div class="form-group">
            <label for="id_title">Title:</label>
            <input id="id_title" maxlength="255" name="title" type="text" class="form-control" />
          </div>
          <div class="form-group">
            <label for="id_abstract">Abstract:</label>
            <textarea id="id_abstract" name="abstract" class="form-control" rows="10"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <a href="#" id="django_link" class="pull-left">Django admin</a>
          <!--button type="button" class="btn btn-default" data-dismiss="modal">Close</button-->
          <button type="button" class="btn btn-default" data-dismiss="modal" onclick="submit_edit()">Save Changes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal" onclick="submit_edit(1)">Discard Entry</button>
          <!--button type="submit" value="save" class="btn btn-primary">Save Changes</button>
          <button type="submit" value="discard" class="btn btn-primary">Discard Entry</button-->
        </div>
      </form>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

website/templates/website/edit_source.html
<html>
<style>
body { font-family:sans-serif; }
form { float:left; }
label { display:block; }
#submitbtn { display:block; margin-top:10px; }
#id_url, #id_default_author, #id_name { width:30em; }
#related { float:left; margin-left:20px; padding:10px; }
ul { list-style-type:none; }
</style>
<script>
function set_name() {
   var f = document.forms[0].elements;
   var au = f['id_default_author'].value;
   var sitetype = f['id_sourcetype'].selectedIndex==0 ?
                     (f['id_url'].value.indexOf('researchgate') > -1 ? 
                        "ResearchGate profile" : "site") 
                     : "blog";
   f['id_name'].value = au+"'s "+sitetype;
}
function update() {
   var f = document.forms[0];
   f.method = 'GET';
   f.submit();
}
window.onload = function(e) {
   cookie_au = getCookie('sauthor');
   var f = document.forms[0].elements;
   var au = f['id_default_author'].value;
   if (cookie_au && !au) f['id_default_author'].value = cookie_au;
   set_name();
}
function getCookie(key) {
   var key_eq = encodeURIComponent(key) + "=";
   var ca = document.cookie.split(';');
   for (var i = 0; i < ca.length; i++) {
      var c = ca[i];
      while (c.charAt(0) === ' ') c = c.substring(1, c.length);
      if (c.indexOf(key_eq) === 0) return decodeURIComponent(c.substring(key_eq.length, c.length));
   }
   return null;
}
</script>
<body>
  
<h2>Add/Edit source</h2>

<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<a href="javascript:void(set_name())">set name</a>
&nbsp; <a href="javascript:void(update())">check related</a>
<input type="submit" id="submitbtn" value="Submit">
</form>

<div id="related">
<h4>Related source pages</h4>
<ul>
{% for src in related %}
   <li>[{{ src.status }}] <a href="{{ src.url }}">{{ src.name }}</a></li>
{% endfor %}
</ul>
</div>

</body>
</html>

website/templates/website/sourceslist.html
{% extends "base.html" %}

{% block content %}

  <h2>Tracked source pages</h2>
  
  <h3>Personal pages</h3>
  <ol class='sources multicol'>
  {% for src in personal %}
    <li>
      <a href='{{ src.url }}' class='src{{ src.status }}'>{{ src.default_author }}</a>{% if src.status > 1%}*{% endif %}
    </li>
  {% endfor %}
  </ol>

  <h3>Repositories</h3>
  <ol class='sources multicol'>
  {% for src in repo %}
    <li>
      <a href='{{ src.url }}' class='src{{ src.status }}'>{{ src.name }}</a>{% if src.status > 1%}*{% endif %}
    </li>
  {% endfor %}
  </ol>

  <h3>Open Access Journals</h3>
  <ol class='sources multicol'>
  {% for src in journal %}
    <li>
      <a href='{{ src.url }}' class='src{{ src.status }}'>{{ src.name }}</a>{% if src.status > 1%}*{% endif %}
    </li>
  {% endfor %}
  </ol>

  <h3>Weblogs</h3>
  <ol class='sources multicol'>
  {% for src in blog %}
    <li>
      <a href='{{ src.url }}' class='src{{ src.status }}'>{{ src.name }}</a>{% if src.status > 1%}*{% endif %}
    </li>
  {% endfor %}
  </ol>
  
  <p>* Sources marked with a star are currently
  inaccessible or don't seem to contain any links to papers.</p>

{% endblock %}